SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 whatsapp VARCHAR(40) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('client','admin') NOT NULL DEFAULT 'client',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS estimates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 job_type VARCHAR(60) NOT NULL,
 input_json JSON NOT NULL,
 status VARCHAR(60) NOT NULL DEFAULT 'PERLU SURVEY',
 estimated_total DECIMAL(18,2) NULL,
 note TEXT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_est_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS surveys (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 estimate_id BIGINT UNSIGNED NULL,
 address TEXT NOT NULL,
 job_type VARCHAR(100) NOT NULL,
 preferred_date DATE NULL,
 scheduled_date DATETIME NULL,
 fee DECIMAL(18,2) NULL,
 notes TEXT NULL,
 status VARCHAR(60) NOT NULL DEFAULT 'menunggu_konfirmasi',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_survey_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 CONSTRAINT fk_survey_est FOREIGN KEY(estimate_id) REFERENCES estimates(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 survey_id BIGINT UNSIGNED NULL,
 project_no VARCHAR(60) NOT NULL UNIQUE,
 title VARCHAR(200) NOT NULL,
 address TEXT NULL,
 job_type VARCHAR(100) NULL,
 status VARCHAR(60) NOT NULL DEFAULT 'persiapan',
 progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
 contract_value DECIMAL(18,2) NULL,
 start_date DATE NULL,
 target_end_date DATE NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_project_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
 CONSTRAINT fk_project_survey FOREIGN KEY(survey_id) REFERENCES surveys(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rabs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 type ENUM('estimasi_awal','final','addendum') NOT NULL,
 version_no INT NOT NULL DEFAULT 1,
 status VARCHAR(60) NOT NULL DEFAULT 'draft',
 grand_total DECIMAL(18,2) NULL,
 notes TEXT NULL,
 approved_at DATETIME NULL,
 locked_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_rab_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rab_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 rab_id BIGINT UNSIGNED NOT NULL,
 item_no INT NOT NULL,
 description VARCHAR(255) NOT NULL,
 volume DECIMAL(14,3) NULL,
 unit VARCHAR(30) NULL,
 unit_price DECIMAL(18,2) NULL,
 subtotal DECIMAL(18,2) NULL,
 created_at DATETIME NOT NULL,
 CONSTRAINT fk_rabitem_rab FOREIGN KEY(rab_id) REFERENCES rabs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contracts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 contract_no VARCHAR(80) NULL UNIQUE,
 contract_value DECIMAL(18,2) NULL,
 scope_text LONGTEXT NULL,
 duration_text VARCHAR(255) NULL,
 payment_terms LONGTEXT NULL,
 rights_obligations LONGTEXT NULL,
 status VARCHAR(60) NOT NULL DEFAULT 'draft',
 signed_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_contract_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS progress_updates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 update_date DATE NOT NULL,
 stage VARCHAR(160) NOT NULL,
 progress_percent TINYINT UNSIGNED NOT NULL,
 description TEXT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_progress_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS progress_photos (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 progress_update_id BIGINT UNSIGNED NOT NULL,
 file_path VARCHAR(255) NOT NULL,
 caption VARCHAR(255) NULL,
 created_at DATETIME NOT NULL,
 CONSTRAINT fk_photo_progress FOREIGN KEY(progress_update_id) REFERENCES progress_updates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 payment_type ENUM('dp','termin','pelunasan') NOT NULL,
 amount DECIMAL(18,2) NOT NULL,
 method VARCHAR(60) NOT NULL DEFAULT 'transfer_bank',
 proof_path VARCHAR(255) NULL,
 status VARCHAR(60) NOT NULL DEFAULT 'menunggu_verifikasi',
 verified_by BIGINT UNSIGNED NULL,
 verified_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_payment_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT,
 CONSTRAINT fk_payment_admin FOREIGN KEY(verified_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS receipts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 payment_id BIGINT UNSIGNED NOT NULL UNIQUE,
 receipt_no VARCHAR(80) NOT NULL UNIQUE,
 issued_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL,
 CONSTRAINT fk_receipt_payment FOREIGN KEY(payment_id) REFERENCES payments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 document_type VARCHAR(60) NOT NULL,
 title VARCHAR(200) NOT NULL,
 file_path VARCHAR(255) NOT NULL,
 client_visible TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 CONSTRAINT fk_document_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS master_prices (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 category VARCHAR(100) NOT NULL,
 name VARCHAR(180) NOT NULL,
 unit VARCHAR(30) NOT NULL,
 price DECIMAL(18,2) NOT NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 INDEX idx_price_category(category),
 INDEX idx_price_active(is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 setting_key VARCHAR(120) NOT NULL UNIQUE,
 setting_value LONGTEXT NULL,
 updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;
