<section class="hero-new" aria-labelledby="hero-title">
  <img class="hero-photo" src="<?= asset('images/company/hero-owner.png') ?>" alt="Visual konstruksi dan supply material pilihan CV BUANA" fetchpriority="high" width="1672" height="941">
  <div class="hero-shade"></div>
  <div class="wrap hero-inner"><div class="hero-copy"><p class="eyebrow light"><span></span> CV BUANA SASTRA DAHANA</p><h1 id="hero-title">Bangun lebih baik.<br><em>Lebih terencana.</em></h1><p class="hero-description">Partner untuk kebutuhan konstruksi, renovasi, dan supply material Anda. Dari rencana awal hingga kebutuhan di lapangan.</p><div class="button-row"><a class="button gold" href="https://wa.me/6281214296499">Konsultasikan Proyek <span aria-hidden="true">↗</span></a><a class="button glass" href="#project">Lihat Proyek <span aria-hidden="true">↓</span></a></div></div><div class="hero-caption"><span>RENCANAKAN. BANGUN. WUJUDKAN.</span><small>Konstruksi &nbsp; / &nbsp; Renovasi &nbsp; / &nbsp; Supply Material</small></div></div>
</section>
<div class="service-ribbon"><div class="wrap"><span>KONSTRUKSI</span><i aria-hidden="true">✦</i><span>RENOVASI</span><i aria-hidden="true">✦</i><span>ALUMINIUM</span><i aria-hidden="true">✦</i><span>SUPPLY MATERIAL</span></div></div>

<section id="tentang" class="section-new"><div class="wrap about-grid">
  <div class="about-visual"><img src="<?= asset('images/company/about-owner.png') ?>" alt="Visual kebersamaan tim pilihan CV BUANA" width="1672" height="941" loading="lazy"><div class="about-seal"><span class="logo-mark"><img src="<?= asset('images/branding/LOGO_CV_BUANA_SASTRA_DAHANA.png') ?>" alt="Logo CV BUANA" loading="lazy"></span><span>CV BUANA<br><strong>SASTRA DAHANA</strong></span></div></div>
  <div class="about-copy"><p class="eyebrow">01 / TENTANG KAMI</p><h2>Membangun ruang.<br><span>Menghubungkan kebutuhan.</span></h2><p>CV BUANA SASTRA DAHANA bergerak dalam layanan konstruksi, renovasi, pekerjaan aluminium, dan supply material bangunan. Berlokasi di Purwakarta, Jawa Barat, kami menjadi tempat Anda memulai pembahasan kebutuhan proyek.</p><p>Setiap rencana memiliki kebutuhan yang berbeda. Mari tentukan lingkup pekerjaan, pilihan material, dan langkah berikutnya melalui konsultasi serta survey.</p><div class="about-details"><span>Berbasis di <strong>Purwakarta, Jawa Barat</strong></span><a class="text-link" href="<?= url('legalitas') ?>">Kenali perusahaan kami <span aria-hidden="true">↗</span></a></div></div>
</div></section>

<section id="layanan" class="section-new services-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">02 / LAYANAN KAMI</p><h2>Satu partner.<br>Beragam kebutuhan.</h2></div><p>Dari pembangunan hingga penyediaan material, bicarakan kebutuhan pekerjaan Anda bersama kami.</p></div><div class="services-grid">
<?php $services = [
['Pembangunan Baru','Rencanakan kebutuhan bangunan Anda, dari lingkup pekerjaan hingga pilihan material.','M4 21V8l8-5 8 5v13M9 21v-7h6v7M8 9h1m6 0h1'],
['Renovasi Rumah & Bangunan','Penyesuaian ruang dan perbaikan bangunan sesuai kebutuhan serta kondisi lapangan.','M3 11l9-8 9 8M5 10v11h14V10M9 21v-7h6v7'],
['Renovasi Gedung & Sekolah','Pembahasan kebutuhan renovasi fasilitas pendidikan dan bangunan lainnya.','M3 21V7h18v14M8 7V3h8v4M7 11h2m6 0h2M7 15h2m6 0h2M10 21v-3h4v3'],
['Pekerjaan Aluminium','Kusen, jendela, dan kebutuhan aluminium dengan spesifikasi yang disepakati.','M4 3h16v18H4zM12 3v18M4 12h16M9 8v1m6 6v1'],
['Supply Material Bangunan','Pengadaan material bangunan untuk mendukung kebutuhan pekerjaan di lapangan.','M3 8l9-5 9 5v9l-9 5-9-5V8Zm0 0 9 5 9-5M12 13v9M7 6l10 5'],
['Pekerjaan Konstruksi Lainnya','Konsultasikan kebutuhan khusus untuk menentukan ruang lingkup pekerjaan.','M14 4a5 5 0 0 0-6 6L3 15l6 6 5-5a5 5 0 0 0 6-6l-4 3-4-4 2-5Z']
]; foreach ($services as $i=>$service): ?><article class="service-card"><div class="service-card-top"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="<?= e($service[2]) ?>"/></svg><span>0<?= $i+1 ?></span></div><h3><?= e($service[0]) ?></h3><p><?= e($service[1]) ?></p><a href="https://wa.me/6281214296499?text=<?= rawurlencode('Halo CV BUANA, saya ingin berkonsultasi tentang '.$service[0].'.') ?>" aria-label="Konsultasi <?= e($service[0]) ?>">Konsultasikan kebutuhan <span aria-hidden="true">↗</span></a></article><?php endforeach; ?>
</div></div></section>

<section id="project" class="section-new"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">03 / PORTOFOLIO</p><h2>Pekerjaan kami,<br>dalam dokumentasi.</h2></div><p>Kenali CV BUANA lebih dekat melalui dokumentasi proyek sekolah yang telah tersedia.</p></div><div class="portfolio-grid">
<?php foreach($projects as $i=>$project): ?><button class="portfolio-card" type="button" data-gallery="<?= e($project['name']) ?>" data-photo="<?= asset($project['image']) ?>" <?php if($project['name']==='SDN 3 Panyindangan'): ?>data-second="<?= asset('images/projects/SDN_3_PANYINDANGAN_02.jpeg') ?>"<?php endif; ?>><div class="project-image"><img src="<?= asset($project['image']) ?>" alt="Dokumentasi <?= e($project['name']) ?>" loading="lazy"><span class="project-open" aria-hidden="true">↗</span></div><div class="project-info"><small>DOKUMENTASI PROYEK / 0<?= $i+1 ?></small><h3><?= e($project['name']) ?></h3></div></button><?php endforeach; ?>
</div></div></section>

<section id="operasional" class="section-new operations-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow light">04 / DUKUNGAN OPERASIONAL</p><h2>Material bangunan.<br>Pekerjaan di lapangan.</h2></div><p>Supply material dan pelaksanaan pekerjaan untuk mendukung kebutuhan konstruksi Anda.</p></div><div class="operations-grid"><figure><img src="<?= asset('images/company/operasional-material.png') ?>" alt="Ilustrasi konstruksi dan supply material pilihan CV BUANA" loading="lazy"><figcaption><span>01 / SUPPLY MATERIAL</span><h3>Konstruksi & Material</h3></figcaption></figure><figure><img src="<?= asset('images/company/operasional-lapangan.jpeg') ?>" alt="Dokumentasi pekerjaan pemasangan material di lapangan" loading="lazy"><figcaption><span>02 / PEKERJAAN LAPANGAN</span><h3>Pelaksanaan Pekerjaan</h3></figcaption></figure></div></div></section>

<section id="profil" class="section-new team-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">05 / PROFIL PERUSAHAAN</p><h2>Kenali orang<br>di balik CV BUANA.</h2></div><p>Kepemimpinan dan dukungan operasional dalam satu perusahaan.</p></div><div class="people-grid"><article class="person-card"><div class="person-photo"><img src="<?= asset('images/team/HALIMUDIN_DIREKTUR_01.png') ?>" alt="Halimudin, Direktur CV BUANA SASTRA DAHANA" loading="lazy"></div><div class="person-copy"><span class="person-role">DIREKTUR</span><h3>Halimudin</h3><p>Halimudin merupakan Direktur CV BUANA SASTRA DAHANA, perusahaan yang bergerak dalam layanan konstruksi, renovasi, dan supply material bangunan.</p><a class="text-link" href="#kontak">Terhubung dengan perusahaan <span aria-hidden="true">↗</span></a></div></article><article class="person-card"><div class="person-photo person-photo--full"><img src="<?= asset('images/team/TEDI_SETIAWAN_01.png') ?>" alt="Tedi Setiawan" loading="lazy"></div><div class="person-copy"><span class="person-role">DIGITAL MARKETING &amp; CREATIVE</span><h3>Tedi Setiawan</h3><p>Tedi Setiawan berperan dalam digital marketing dan creative CV BUANA SASTRA DAHANA.</p><a class="text-link" href="https://wa.me/62882000119208">Hubungi admin layanan <span aria-hidden="true">↗</span></a></div></article><article class="person-card person-card--identity"><div class="adya-portrait"><img src="<?= asset('images/team/ADYA_WAKIL_DIREKTUR.png') ?>" alt="M. Adya H.A., Wakil Direktur CV BUANA SASTRA DAHANA" loading="lazy"></div><div class="person-copy"><span class="person-role">WAKIL DIREKTUR</span><h3>M. Adya H.A.</h3><p>M. Adya H.A. merupakan Wakil Direktur CV BUANA SASTRA DAHANA.</p></div></article></div></div></section>

<section class="portal-section"><div class="wrap portal-promo"><div><p class="eyebrow">PORTAL CLIENT CV BUANA</p><h2>Lebih dekat dengan<br>informasi proyek Anda.</h2><p>Akses portal melalui halaman login client. Satu pintu untuk melihat informasi proyek yang tersedia bagi akun Anda.</p><a class="button dark" href="<?= url('login') ?>"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></svg>Unduh Aplikasi <span aria-hidden="true">↗</span></a><small class="portal-note">Membuka login client · Akses melalui browser</small></div><div class="portal-visual" aria-hidden="true"><div class="portal-orbit"></div><div class="portal-preview"><div class="preview-top"><span class="logo-mark"><img src="<?= asset('images/branding/LOGO_CV_BUANA_SASTRA_DAHANA.png') ?>" alt="" loading="lazy"></span><span>CV BUANA<strong>Portal Client</strong></span><i></i></div><div class="preview-body"><span class="preview-label">RUANG INFORMASI ANDA</span><h3>Proyek Anda.<br>Dalam satu portal.</h3><div class="preview-item"><span>01</span> Informasi proyek <b>↗</b></div><div class="preview-item"><span>02</span> RAB & kontrak <b>↗</b></div><div class="preview-item"><span>03</span> Pembayaran & dokumen <b>↗</b></div><div class="preview-login">Login Client <span>→</span></div></div></div></div></div></section>

<section id="kontak" class="section-new contact-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">06 / MARI TERHUBUNG</p><h2>Rencana Anda,<br>dimulai dari percakapan.</h2></div><a class="button gold" href="https://wa.me/6281214296499">Konsultasi via WhatsApp <span aria-hidden="true">↗</span></a></div><div class="contact-grid-new"><div class="contact-address"><span class="detail-label">KANTOR & ALAMAT PERUSAHAAN</span><h3>CV BUANA SASTRA DAHANA</h3><address>Jl. Sukatani, Kp. Cikadu RT 019 / RW 006, Desa Sukatani, Kecamatan Sukatani, Kabupaten Purwakarta, Jawa Barat 41167, Indonesia.</address><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=<?= rawurlencode('Jl. Sukatani, Kp. Cikadu RT 019 RW 006, Desa Sukatani, Kecamatan Sukatani, Purwakarta, Jawa Barat 41167') ?>" target="_blank" rel="noopener noreferrer">Cari alamat di Google Maps <span aria-hidden="true">↗</span></a></div><div class="contact-channels"><div><span class="detail-label">TELEPON / WHATSAPP</span><a href="https://wa.me/6281214296499">0812-1429-6499 <span>↗</span></a></div><div><span class="detail-label">ADMIN LAYANAN</span><a href="https://wa.me/62882000119208">0882-0001-19208 <span>↗</span></a></div><div><span class="detail-label">EMAIL PERUSAHAAN</span><a href="mailto:Buanasastradahana@gmail.com">Buanasastradahana@gmail.com <span>↗</span></a></div><div><span class="detail-label">CUSTOMER SERVICE</span><a href="mailto:customerservice@buanasastradahana.online">customerservice@buanasastradahana.online <span>↗</span></a></div></div><div class="contact-qr"><img src="<?= asset('images/contact/QR_CODE_LOKASI_GOOGLE_MAPS.png') ?>" alt="QR lokasi Google Maps CV BUANA" loading="lazy"><span>Pindai untuk lokasi</span><img class="siplah-logo" src="<?= asset('images/ecommerce/LOGO_SIPLAH_ECOMMERCE.png') ?>" alt="SIPLah TokoLadang" loading="lazy"></div></div></div></section>
<dialog class="gallery-dialog" aria-labelledby="gallery-title"><div class="gallery-head"><div><small>DOKUMENTASI PROYEK</small><h2 id="gallery-title"></h2></div><button type="button" class="gallery-close" aria-label="Tutup galeri">×</button></div><div class="gallery-images"></div></dialog>
